### ISSUE TITLE
Wrongly accuses IDN to be malicious

### ISSUE THREAD

**Issue by frodegill** [phishai/idn-protect-chrome#3] opened 2018-03-27 08:16 UTC
I've looked through the code, and the whole plugin is based on the flawed assumption that IDN domains are malicious (ALL of them!). Not only is this wrong for basically the whole world except USA, but it is also flawed. I have a domain turfølge.no . If a phisher is registering turfolge.no, then *that* domain is the malicious one (my domain was registered first). idn-protect-chrome will currently in no way be able to say that turfolge.no is malicious, but will say that turfølge.no is malicious even if turfolge.no isn't even currently registered.

**Comment by LawnSounds** [comment] 2018-03-27 09:16
Duplicate of #2

**Comment by frodegill** [comment] 2018-03-27 09:34
I do not agree in that this is a duplicate of #2. #2 is about IDNs being penalized (which they are), #3 covers penalizing ASCII domains if it is the ASCII version that is used for phishing.

**Comment by yevgenypats** [comment] 2018-03-27 11:48
Hey @frodegill,

First, Thanks for taking the time and bringing this up.
Second, It doesn't matter if it is a duplicate or not of #2 but I'll take the time here and explain the purpose of this repo (I'll update the readme in the upcoming week).

This repo is part of our move open-sourcing big parts of our product, I wrote a blog post about it [here](https://www.phish.ai/2018/03/26/phish-ai-love-open-source/).

Regarding the IDN feature it's just a feature and it is indeed was intended only as a small use case for people/companies that do not access IDN domains usually and help them get an alert on any IDN domain (because chrome doesn't) .

Moreover, I don't believe the right way to detect phishing both IDN based or not is with any kind of heuristics and rules because it's usually very easily circumvented IMO - (we can have a discussion in a different post or in this one and if this feature get's a lot of upvotes I'll consider going for it).

The main feature of [phish.ai](https://phish.ai/product/) is AI and Computer Vision. TLDR of the website: what we essentially do is we crawl legit websites store them in a Computer Vision based db (if that a good analogy) and then from the client side we upload screenshots for websites that we are unfamiliar with and compare them using a reverse search with our database and then compare the domain on which the site is hosted (essentially just like a human would do). This technique is agnostic of whether the domain is IDN or not and IMO make a lot of of phishing solutions redundant including heuristics and rules for detecting IDN based attacks.


I'll also address the roadmap of this repo:
role out to firefox/opera/edge (just the small feature) - This week.
role out phish.AI detection - Next Week.

Hope I answered some of the misunderstandings.

**Comment by yevgenypats** [comment] 2018-03-27 12:04
Something that I will do regarding this issue is changing the block screen to a different one from malicious site ahead to IDN website ahead and showing the malicious site ahead only if we really believe it's malicious.

**Comment by frodegill** [comment] 2018-03-27 12:30
In this case, the extension should be clearly marked as being suited for people that visits pages with us-ascii characters domain names ONLY (which is a very small market, probably only subset of USA), as the current version is the equivalent of marking all web pages with encoding not us-ascii as phishing sites.

Chrome has a very good algorithm for detecting problematic IDNs (based on even more good work from the Firefox developers). See https://www.chromium.org/developers/design-documents/idn-in-google-chrome . If you implement something similiar you are doing something good. Now you are only hurting domain owners around the globe.

**Comment by yevgenypats** [comment] 2018-03-27 12:34
@frodegill I agree with the clarification and I'll add it to the readme today. I don't agree with the "very good algorithm for detecting problematic IDNs"  as it's very easy to circumvent thus I don't believe this is the way to go. Take a look at this [example](https://www.phish.ai/2018/03/13/idn-homograph-attack-back-crypto/)

**Comment by frodegill** [comment] 2018-03-27 12:55
In the example one of the domain names has a b look-alike character. This is probably the easiest of all IDN phishing attempts to detect, and in the document I linked above several tests would fail (first and foremost, http://www.unicode.org/reports/tr39/#Restriction_Level_Detection would fail all the way down to level "5. Minimally Restrictive"). If your code implemented the Chrome algorithm, it would correctly flag your example as a phishing attempt, but not have false positives for all the legitime IDN domain names.

**Comment by yevgenypats** [comment] 2018-03-27 13:02
I Agree that this example is easy to detect but the point is that this is just one of many examples and the whole idea with rules for idn based detection are a cat and mouse game and this is not where we taking the project currently. As we role out the AI and Computer Vision  algorithm such example will be detected and you would be able to opt-out from blocking all the unicode domains. hope it makes things clear. Also I'll change the name of the repo to avoid misunderstandings.

**Comment by yevgenypats** [comment] 2018-04-06 06:43
Closing this issue as the repo name was changed. The IDN protection is now an option and can be opt-out.

**Closed as completed** 2018-04-06 06:43 UTC
